### REQUEST SCHEMA
POST {{host}}/api/meta:request:schema/AccountService
Content-Type: application/json

### REQUEST EXAMPLE
POST {{host}}/api/meta:request:example/AccountService
Content-Type: application/json

### RESPONSE SCHEMA
POST {{host}}/api/meta:response:schema/AccountService
Content-Type: application/json

### RESPONSE EXAMPLE
POST {{host}}/api/meta:response:example/AccountService
Content-Type: application/json

### SAMPLE OPEN
POST {{host}}/api/call/AccountService
Content-Type: application/json
codeworks-prefs-schema-check: None

{
  "trigger": "Open",
  "identifier": "{{$guid}}",
  "open": {
    "name": "Test Account",
    "initialBalance": 50.0,
    "ssn": "123456789"
  }
}

### PAUSE ACCOUNT
POST {{host}}/api/call/AccountService
Content-Type: application/json

{
  "identifier": "f95a278b-4e8c-4d19-a0ba-60ea88381db4",
  "trigger": "Pause"
}

### PAUSE ACCOUNT
POST {{host}}/api/call/AccountService
Content-Type: application/json

{
  "identifier": "f95a278b-4e8c-4d19-a0ba-60ea88381db4",
  "trigger": "Reopen",
  "reopen": {}
}

### SAMPLE UPDATE
POST {{host}}/api/call/AccountService
Content-Type: application/json

{
  "trigger": "Update",
  "identifier": "c09a437d-7215-4cb2-bcda-00d5f70a7514",
  "update": {
    "name": "Updated Account"
  }
}