### REQUEST SCHEMA
POST {{host}}/api/meta:request:schema/AccountService
Content-Type: application/json

### REQUEST DIAGRAM
POST {{host}}/api/meta:state:diagram/AccountService
Content-Type: application/json

### REQUEST DIAGRAM
POST {{host}}/api/meta:state:diagram:view/AccountService
Content-Type: application/json

### REQUEST EXAMPLE
POST {{host}}/api/meta:request:example/AccountService
Content-Type: application/json

### RESPONSE SCHEMA
POST {{host}}/api/meta:response:schema/AccountService
Content-Type: application/json

### RESPONSE EXAMPLE
POST {{host}}/api/meta:response:example/AccountService
Content-Type: application/json

### SAMPLE OPEN
POST {{host}}/api/call/AccountService
Content-Type: application/json
codeworks-prefs-schema-check: None

{
  "trigger": "Open",
  "identifier": "{{$guid}}",
  "open": {
    "name": "Test Account",
    "initialBalance": 50.0,
    "ssn": "123456785"
  }
}

### PAUSE ACCOUNT
POST {{host}}/api/call/AccountService
Content-Type: application/json

{
  "identifier": "f7e1a6c1-e8e7-4d9a-a384-1bb7b63a9ea4",
  "trigger": "Pause"
}

### PAUSE ACCOUNT
POST {{host}}/api/call/AccountService
Content-Type: application/json

{
  "identifier": "05df85d0-1b7c-4008-b904-0a0992c27523",
  "trigger": "Reopen",
  "reopen": {}
}

### SAMPLE UPDATE
POST {{host}}/api/call/AccountService
Content-Type: application/json
codeworks-prefs-schema-check: None

{
  "trigger": "Update",
  "identifier": "4b23e5c4-e086-45e1-8d9f-9cc49694f7f7",
  "update": {
    "name": "Test"
  },
  "correlationId": "{{$guid}}"
}

### SAMPLE UPDATE
POST {{host}}/api/call/AccountService
Content-Type: application/json

{
  "identifier": "fc2472bf-f05c-49e1-b092-8e3f28cef9fc"
}