### REQUEST SCHEMA
POST {{host}}/api/meta:request:schema/SignedInService
Content-Type: application/json

### REQUEST DIAGRAM
POST {{host}}/api/meta:state:diagram/SignedInService
Content-Type: application/json

### REQUEST DIAGRAM
POST {{host}}/api/meta:state:diagram:view/SignedInService
Content-Type: application/json

### REQUEST EXAMPLE
POST {{host}}/api/meta:request:example/SignedInService
Content-Type: application/json

### RESPONSE SCHEMA
POST {{host}}/api/meta:response:schema/SignedInService
Content-Type: application/json

### RESPONSE EXAMPLE
POST {{host}}/api/meta:response:example/SignedInService
Content-Type: application/json

### SAMPLE CALL
POST {{host}}/api/call/SignedInService
Content-Type: application/json
codeworks-prefs-schema-check: None

{
  "correlationId": "{{$guid}}",
  "authToken": "D"
}

### PAUSE ACCOUNT
POST {{host}}/api/call/SignedInService
Content-Type: application/json

{
  "identifier": "fc2472bf-f05c-49e1-b092-8e3f28cef9fc",
  "trigger": "Pause"
}

### PAUSE ACCOUNT
POST {{host}}/api/call/SignedInService
Content-Type: application/json

{
  "identifier": "fc2472bf-f05c-49e1-b092-8e3f28cef9fc",
  "trigger": "Reopen",
  "reopen": {}
}

### SAMPLE UPDATE
POST {{host}}/api/call/SignedInService
Content-Type: application/json

{
  "trigger": "Update",
  "identifier": "fc2472bf-f05c-49e1-b092-8e3f28cef9fc",
  "update": {
    "name": "Updated Account {{$timestamp}}"
  }
}

### SAMPLE UPDATE
POST {{host}}/api/call/SignedInService
Content-Type: application/json

{
  "identifier": "fc2472bf-f05c-49e1-b092-8e3f28cef9fc"
}