name: .NET

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Deploy CodeWorks Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        NUGET_KEY: ${{ secrets.nuget_key }}
        PROJECT_FILE_PATH: Gtt.CodeWorks/Gtt.CodeWorks.csproj
        TAG_FORMAT: Gtt.CodeWorks.* 
    
    - name: Deploy CodeWorks.Serializers.TextJson Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        NUGET_KEY: ${{ secrets.nuget_key }}
        PROJECT_FILE_PATH: Gtt.CodeWorks.Serializers.TextJson/Gtt.CodeWorks.Serializers.TextJson.csproj
        TAG_FORMAT: Gtt.CodeWorks.Serializers.TextJson.*
    
    - name: Deploy Gtt.CodeWorks.DataAnnotations Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        NUGET_KEY: ${{ secrets.nuget_key }}
        PROJECT_FILE_PATH: Gtt.CodeWorks.DataAnnotations/Gtt.CodeWorks.DataAnnotations.csproj
        TAG_FORMAT: Gtt.CodeWorks.DataAnnotations.*
    
    - name: Deploy Gtt.CodeWorks.EasyNetQ Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        NUGET_KEY: ${{ secrets.nuget_key }}
        PROJECT_FILE_PATH: Gtt.CodeWorks.EasyNetQ/Gtt.CodeWorks.EasyNetQ.csproj
        TAG_FORMAT: Gtt.CodeWorks.EasyNetQ.*
        
    - name: Deploy Gtt.CodeWorks.Functions.Host Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        NUGET_KEY: ${{ secrets.nuget_key }}
        PROJECT_FILE_PATH: Gtt.CodeWorks.Functions.Host/Gtt.CodeWorks.Functions.Host.csproj
        TAG_FORMAT: Gtt.CodeWorks.Functions.Host.*
        
        

    
